name: black
# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - name: black
      uses: RojerGS/python-black-check@master
